# Generated by Django 4.2 on 2023-06-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='email',
            field=models.EmailField(default='modelo@modelo.com', max_length=254),
        ),
    ]
