# Generated by Django 4.2 on 2023-05-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesional', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesional',
            name='servicio',
        ),
        migrations.AddField(
            model_name='profesional',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
