# Generated by Django 4.2 on 2023-06-17 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.FloatField()),
                ('duracion', models.DurationField(default=datetime.timedelta(seconds=1800))),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
