# Generated by Django 4.2 on 2023-06-01 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicio', '0001_initial'),
        ('profesional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfesionalServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_borrado', models.DateField(null=True)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesional.profesional')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.servicio')),
            ],
        ),
    ]
