# Generated by Django 4.2 on 2023-06-17 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesionalservicio', '0001_initial'),
        ('servicio', '0001_initial'),
        ('turno', '0001_initial'),
        ('profesional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesionalservicio',
            name='fecha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turno.fecha'),
        ),
        migrations.AddField(
            model_name='profesionalservicio',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turno.horario'),
        ),
        migrations.AddField(
            model_name='profesionalservicio',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesional.profesional'),
        ),
        migrations.AddField(
            model_name='profesionalservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.servicio'),
        ),
    ]
