# Generated by Django 4.2 on 2023-05-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionalservicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesionalservicio',
            name='fecha_borrado',
            field=models.DateField(null=True),
        ),
    ]
