# Generated by Django 4.2 on 2023-06-17 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0001_initial'),
        ('profesionalservicio', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesionalservicio',
            name='fecha',
            field=models.ForeignKey(default=481, on_delete=django.db.models.deletion.CASCADE, to='turno.fecha'),
        ),
        migrations.AlterField(
            model_name='profesionalservicio',
            name='horario',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='turno.horario'),
        ),
    ]
