# Generated by Django 4.2 on 2023-06-17 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesionalservicio', '0003_alter_profesionalservicio_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesionalservicio',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='profesionalservicio',
            name='horario',
        ),
    ]
