# Generated by Django 4.2 on 2023-06-17 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turno',
            old_name='servicio',
            new_name='profesional_servicio',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='profesional',
        ),
    ]
